#!/usr/bin/env bash
#
# Vim Pastebin - Edit macOS clipboard contents in Vim and save changes back to the clipboard.

set -e
trap 'echo "error on line ${LINENO}"' ERR

readonly SCRIPT_NAME=vipb

err() {
  echo 1>&2 "$@"
}

usage() {
  err "usage: ${SCRIPT_NAME} [-h|--help]"
  err ""
  err "    -h | --help    display usage"
  exit 1
}

main() {
  args=()
  while (( $# > 0 )); do
    key=$1
    case "${key}" in
      -h|--help)
        usage
        ;;
      *)
        args+=("$1")
        shift
        ;;
    esac
  done
  set -- "${args[@]}"

  readonly tmpfile=$(mktemp -t "${SCRIPT_NAME}")

  pbpaste > "${tmpfile}"
  vim "${tmpfile}"
  <"${tmpfile}" pbcopy
  rm -f "${tmpfile}"
}

main $@
